name: 'cyberduck-cli'
description: 'Cyberduck for the command line interface (CLI).'
branding:
  icon: 'upload-cloud'
  color: 'yellow'
inputs:
  mode:
    description: 'Mode to run'
    required: true
  url:
    description: 'Remote URL'
    required: true
  path:
    description: 'Local relative path'
    required: false
  args:
    description: 'Additional arguments'
    required: false
outputs:
  log:
    description: "Cyberduck CLI output"
runs:
  using: 'docker'
  image: 'Dockerfile'
